language: node_js
node_js:
  - 16

services:
  - docker

# Pre-testing installs
install:
  - echo "Test for TravisCI install"

# Scripts to be run such as tests
before_script:
  - echo "Test for TravisCI before_script"

script:
  - docker --version # print the version for logging
  - docker build -t udagram-api-feed:v$TRAVIS_BUILD_NUMBER ./udagram-api-feed
  - docker tag udagram-api-feed:v$TRAVIS_BUILD_NUMBER $DOCKER_USERNAME/udagram-api-feed:v$TRAVIS_BUILD_NUMBER

  - docker build -t udagram-api-user:v$TRAVIS_BUILD_NUMBER ./udagram-api-user
  - docker tag udagram-api-user:v$TRAVIS_BUILD_NUMBER $DOCKER_USERNAME/udagram-api-user:v$TRAVIS_BUILD_NUMBER

  - docker build -t udagram-frontend:v$TRAVIS_BUILD_NUMBER ./udagram-frontend
  - docker tag udagram-frontend:v$TRAVIS_BUILD_NUMBER $DOCKER_USERNAME/udagram-frontend:v$TRAVIS_BUILD_NUMBER

  - docker build -t reverseproxy:v$TRAVIS_BUILD_NUMBER ./udagram-reverseproxy
  - docker tag reverseproxy:v$TRAVIS_BUILD_NUMBER $DOCKER_USERNAME/reverseproxy:v$TRAVIS_BUILD_NUMBER

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push $DOCKER_USERNAME/udagram-api-feed:v$TRAVIS_BUILD_NUMBER
  - docker push $DOCKER_USERNAME/udagram-api-user:v$TRAVIS_BUILD_NUMBER
  - docker push $DOCKER_USERNAME/udagram-frontend:v$TRAVIS_BUILD_NUMBER
  - docker push $DOCKER_USERNAME/reverseproxy:v$TRAVIS_BUILD_NUMBER
